name: Build and Deploy Lambdas

on:
  push:
    branches: ["master"] # change to "main" if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build TypeScript -> dist/
      - name: Build TypeScript
        run: npm run build

      # 5. Install production-only dependencies
      - name: Install production dependencies
        run: npm install --only=production

      # 6. Package SubmitApplication Lambda
      - name: Package SubmitApplication
        run: |
          mkdir -p package-submit/lambdas
          cp dist/lambdas/submitApplication.js package-submit/lambdas/
          cp -r node_modules package-submit/
          cp package.json package-submit/
          cd package-submit
          zip -r ../submitApplication.zip .

      # 7. Deploy SubmitApplication Lambda
      - name: Deploy SubmitApplication
        run: |
          aws lambda update-function-code \
            --function-name SubmitApplication \
            --zip-file fileb://submitApplication.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      # 8. Package OutboxProcessor Lambda
      - name: Package OutboxProcessor
        run: |
          mkdir -p package-outbox/lambdas
          cp dist/lambdas/outboxProcessor.js package-outbox/lambdas/
          cp -r node_modules package-outbox/
          cp package.json package-outbox/
          cd package-outbox
          zip -r ../outboxProcessor.zip .

      # 9. Deploy OutboxProcessor Lambda
      - name: Deploy OutboxProcessor
        run: |
          aws lambda update-function-code \
            --function-name OutboxProcessor \
            --zip-file fileb://outboxProcessor.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
